/* eslint-disable */
import * as types from "./graphql";
import type { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
  "query Dashboard($from: DateTime!, $to: DateTime!, $recentReposFirst: Int!, $todoFirst: Int!, $reviewRequestQuery: String!, $issueAssignmentQuery: String!, $authoredPrQuery: String!) {\n  viewer {\n    id\n    login\n    name\n    company\n    repositories(\n      first: $recentReposFirst\n      affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]\n      orderBy: {field: PUSHED_AT, direction: DESC}\n      isFork: false\n    ) {\n      totalCount\n      nodes {\n        id\n        name\n        nameWithOwner\n        url\n        updatedAt\n        pushedAt\n        isPrivate\n        primaryLanguage {\n          name\n          color\n        }\n        issues(states: OPEN) {\n          totalCount\n        }\n        pullRequests(states: OPEN) {\n          totalCount\n        }\n      }\n    }\n    contributionsCollection(from: $from, to: $to) {\n      totalCommitContributions\n      totalPullRequestContributions\n      totalIssueContributions\n      totalPullRequestReviewContributions\n    }\n  }\n  reviewRequests: search(\n    query: $reviewRequestQuery\n    type: ISSUE\n    first: $todoFirst\n  ) {\n    issueCount\n    nodes {\n      __typename\n      ... on PullRequest {\n        id\n        number\n        title\n        url\n        updatedAt\n        reviewDecision\n        repository {\n          nameWithOwner\n          url\n        }\n        author {\n          login\n        }\n        comments {\n          totalCount\n        }\n      }\n    }\n  }\n  issueAssignments: search(\n    query: $issueAssignmentQuery\n    type: ISSUE\n    first: $todoFirst\n  ) {\n    issueCount\n    nodes {\n      __typename\n      ... on Issue {\n        id\n        number\n        title\n        url\n        updatedAt\n        state\n        repository {\n          nameWithOwner\n          url\n        }\n        comments {\n          totalCount\n        }\n      }\n    }\n  }\n  authoredPullRequests: search(\n    query: $authoredPrQuery\n    type: ISSUE\n    first: $todoFirst\n  ) {\n    issueCount\n  }\n}": typeof types.DashboardDocument;
  'query RepositoryDetail($owner: String!, $name: String!, $rootExpression: String!, $readmeExpression: String!) {\n  repository(owner: $owner, name: $name) {\n    id\n    name\n    nameWithOwner\n    url\n    description\n    homepageUrl\n    createdAt\n    updatedAt\n    pushedAt\n    isPrivate\n    visibility\n    viewerPermission\n    stargazerCount\n    forkCount\n    watchers {\n      totalCount\n    }\n    issues(states: OPEN) {\n      totalCount\n    }\n    pullRequests(states: OPEN) {\n      totalCount\n    }\n    primaryLanguage {\n      name\n      color\n    }\n    languages(first: 6, orderBy: {field: SIZE, direction: DESC}) {\n      edges {\n        size\n        node {\n          id\n          name\n          color\n        }\n      }\n    }\n    owner {\n      __typename\n      login\n      ... on User {\n        name\n      }\n      ... on Organization {\n        name\n      }\n    }\n    defaultBranchRef {\n      name\n      target {\n        __typename\n        ... on Commit {\n          history(first: 1) {\n            totalCount\n          }\n          committedDate\n          messageHeadline\n          author {\n            name\n            user {\n              login\n              avatarUrl(size: 40)\n              url\n            }\n          }\n        }\n      }\n    }\n    refs(\n      refPrefix: "refs/heads/"\n      first: 10\n      orderBy: {field: ALPHABETICAL, direction: ASC}\n    ) {\n      totalCount\n      nodes {\n        id\n        name\n        target {\n          __typename\n          ... on Commit {\n            committedDate\n            messageHeadline\n            author {\n              name\n              user {\n                login\n              }\n            }\n          }\n        }\n      }\n    }\n    rootEntries: object(expression: $rootExpression) {\n      __typename\n      ... on Tree {\n        entries {\n          name\n          type\n          oid\n          mode\n          object {\n            __typename\n            ... on Blob {\n              byteSize\n              isBinary\n            }\n          }\n        }\n      }\n    }\n    readme: object(expression: $readmeExpression) {\n      __typename\n      ... on Blob {\n        byteSize\n        isBinary\n        text\n      }\n    }\n  }\n}': typeof types.RepositoryDetailDocument;
  "query Viewer {\n  viewer {\n    id\n    login\n    name\n    avatarUrl(size: 80)\n    url\n    company\n  }\n}": typeof types.ViewerDocument;
  "query ViewerProfile($from: DateTime!, $to: DateTime!) {\n  viewer {\n    id\n    login\n    name\n    avatarUrl(size: 160)\n    url\n    email\n    company\n    location\n    websiteUrl\n    bio\n    createdAt\n    followers {\n      totalCount\n    }\n    following {\n      totalCount\n    }\n    organizations(first: 10) {\n      totalCount\n      nodes {\n        id\n        login\n        name\n        url\n        avatarUrl(size: 40)\n      }\n    }\n    repositories(\n      first: 5\n      affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]\n      orderBy: {field: PUSHED_AT, direction: DESC}\n      isFork: false\n    ) {\n      totalCount\n      nodes {\n        id\n        name\n        nameWithOwner\n        url\n        viewerPermission\n        updatedAt\n        isPrivate\n      }\n    }\n    contributionsCollection(from: $from, to: $to) {\n      totalCommitContributions\n      totalPullRequestContributions\n      totalIssueContributions\n      totalPullRequestReviewContributions\n    }\n  }\n}": typeof types.ViewerProfileDocument;
  "query ViewerRepositories($first: Int!, $after: String) {\n  viewer {\n    repositories(\n      first: $first\n      after: $after\n      affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]\n      orderBy: {field: PUSHED_AT, direction: DESC}\n    ) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      nodes {\n        id\n        name\n        nameWithOwner\n        url\n        description\n        isPrivate\n        visibility\n        pushedAt\n        updatedAt\n        viewerPermission\n        stargazerCount\n        forkCount\n        primaryLanguage {\n          name\n          color\n        }\n        owner {\n          __typename\n          login\n          avatarUrl(size: 40)\n          ... on Organization {\n            name\n          }\n          ... on User {\n            name\n          }\n        }\n        issues(states: OPEN) {\n          totalCount\n        }\n        pullRequests(states: OPEN) {\n          totalCount\n        }\n        defaultBranchRef {\n          name\n          target {\n            __typename\n            ... on Commit {\n              history(first: 1) {\n                totalCount\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}": typeof types.ViewerRepositoriesDocument;
};
const documents: Documents = {
  "query Dashboard($from: DateTime!, $to: DateTime!, $recentReposFirst: Int!, $todoFirst: Int!, $reviewRequestQuery: String!, $issueAssignmentQuery: String!, $authoredPrQuery: String!) {\n  viewer {\n    id\n    login\n    name\n    company\n    repositories(\n      first: $recentReposFirst\n      affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]\n      orderBy: {field: PUSHED_AT, direction: DESC}\n      isFork: false\n    ) {\n      totalCount\n      nodes {\n        id\n        name\n        nameWithOwner\n        url\n        updatedAt\n        pushedAt\n        isPrivate\n        primaryLanguage {\n          name\n          color\n        }\n        issues(states: OPEN) {\n          totalCount\n        }\n        pullRequests(states: OPEN) {\n          totalCount\n        }\n      }\n    }\n    contributionsCollection(from: $from, to: $to) {\n      totalCommitContributions\n      totalPullRequestContributions\n      totalIssueContributions\n      totalPullRequestReviewContributions\n    }\n  }\n  reviewRequests: search(\n    query: $reviewRequestQuery\n    type: ISSUE\n    first: $todoFirst\n  ) {\n    issueCount\n    nodes {\n      __typename\n      ... on PullRequest {\n        id\n        number\n        title\n        url\n        updatedAt\n        reviewDecision\n        repository {\n          nameWithOwner\n          url\n        }\n        author {\n          login\n        }\n        comments {\n          totalCount\n        }\n      }\n    }\n  }\n  issueAssignments: search(\n    query: $issueAssignmentQuery\n    type: ISSUE\n    first: $todoFirst\n  ) {\n    issueCount\n    nodes {\n      __typename\n      ... on Issue {\n        id\n        number\n        title\n        url\n        updatedAt\n        state\n        repository {\n          nameWithOwner\n          url\n        }\n        comments {\n          totalCount\n        }\n      }\n    }\n  }\n  authoredPullRequests: search(\n    query: $authoredPrQuery\n    type: ISSUE\n    first: $todoFirst\n  ) {\n    issueCount\n  }\n}":
    types.DashboardDocument,
  'query RepositoryDetail($owner: String!, $name: String!, $rootExpression: String!, $readmeExpression: String!) {\n  repository(owner: $owner, name: $name) {\n    id\n    name\n    nameWithOwner\n    url\n    description\n    homepageUrl\n    createdAt\n    updatedAt\n    pushedAt\n    isPrivate\n    visibility\n    viewerPermission\n    stargazerCount\n    forkCount\n    watchers {\n      totalCount\n    }\n    issues(states: OPEN) {\n      totalCount\n    }\n    pullRequests(states: OPEN) {\n      totalCount\n    }\n    primaryLanguage {\n      name\n      color\n    }\n    languages(first: 6, orderBy: {field: SIZE, direction: DESC}) {\n      edges {\n        size\n        node {\n          id\n          name\n          color\n        }\n      }\n    }\n    owner {\n      __typename\n      login\n      ... on User {\n        name\n      }\n      ... on Organization {\n        name\n      }\n    }\n    defaultBranchRef {\n      name\n      target {\n        __typename\n        ... on Commit {\n          history(first: 1) {\n            totalCount\n          }\n          committedDate\n          messageHeadline\n          author {\n            name\n            user {\n              login\n              avatarUrl(size: 40)\n              url\n            }\n          }\n        }\n      }\n    }\n    refs(\n      refPrefix: "refs/heads/"\n      first: 10\n      orderBy: {field: ALPHABETICAL, direction: ASC}\n    ) {\n      totalCount\n      nodes {\n        id\n        name\n        target {\n          __typename\n          ... on Commit {\n            committedDate\n            messageHeadline\n            author {\n              name\n              user {\n                login\n              }\n            }\n          }\n        }\n      }\n    }\n    rootEntries: object(expression: $rootExpression) {\n      __typename\n      ... on Tree {\n        entries {\n          name\n          type\n          oid\n          mode\n          object {\n            __typename\n            ... on Blob {\n              byteSize\n              isBinary\n            }\n          }\n        }\n      }\n    }\n    readme: object(expression: $readmeExpression) {\n      __typename\n      ... on Blob {\n        byteSize\n        isBinary\n        text\n      }\n    }\n  }\n}':
    types.RepositoryDetailDocument,
  "query Viewer {\n  viewer {\n    id\n    login\n    name\n    avatarUrl(size: 80)\n    url\n    company\n  }\n}":
    types.ViewerDocument,
  "query ViewerProfile($from: DateTime!, $to: DateTime!) {\n  viewer {\n    id\n    login\n    name\n    avatarUrl(size: 160)\n    url\n    email\n    company\n    location\n    websiteUrl\n    bio\n    createdAt\n    followers {\n      totalCount\n    }\n    following {\n      totalCount\n    }\n    organizations(first: 10) {\n      totalCount\n      nodes {\n        id\n        login\n        name\n        url\n        avatarUrl(size: 40)\n      }\n    }\n    repositories(\n      first: 5\n      affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]\n      orderBy: {field: PUSHED_AT, direction: DESC}\n      isFork: false\n    ) {\n      totalCount\n      nodes {\n        id\n        name\n        nameWithOwner\n        url\n        viewerPermission\n        updatedAt\n        isPrivate\n      }\n    }\n    contributionsCollection(from: $from, to: $to) {\n      totalCommitContributions\n      totalPullRequestContributions\n      totalIssueContributions\n      totalPullRequestReviewContributions\n    }\n  }\n}":
    types.ViewerProfileDocument,
  "query ViewerRepositories($first: Int!, $after: String) {\n  viewer {\n    repositories(\n      first: $first\n      after: $after\n      affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]\n      orderBy: {field: PUSHED_AT, direction: DESC}\n    ) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      nodes {\n        id\n        name\n        nameWithOwner\n        url\n        description\n        isPrivate\n        visibility\n        pushedAt\n        updatedAt\n        viewerPermission\n        stargazerCount\n        forkCount\n        primaryLanguage {\n          name\n          color\n        }\n        owner {\n          __typename\n          login\n          avatarUrl(size: 40)\n          ... on Organization {\n            name\n          }\n          ... on User {\n            name\n          }\n        }\n        issues(states: OPEN) {\n          totalCount\n        }\n        pullRequests(states: OPEN) {\n          totalCount\n        }\n        defaultBranchRef {\n          name\n          target {\n            __typename\n            ... on Commit {\n              history(first: 1) {\n                totalCount\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}":
    types.ViewerRepositoriesDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query Dashboard($from: DateTime!, $to: DateTime!, $recentReposFirst: Int!, $todoFirst: Int!, $reviewRequestQuery: String!, $issueAssignmentQuery: String!, $authoredPrQuery: String!) {\n  viewer {\n    id\n    login\n    name\n    company\n    repositories(\n      first: $recentReposFirst\n      affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]\n      orderBy: {field: PUSHED_AT, direction: DESC}\n      isFork: false\n    ) {\n      totalCount\n      nodes {\n        id\n        name\n        nameWithOwner\n        url\n        updatedAt\n        pushedAt\n        isPrivate\n        primaryLanguage {\n          name\n          color\n        }\n        issues(states: OPEN) {\n          totalCount\n        }\n        pullRequests(states: OPEN) {\n          totalCount\n        }\n      }\n    }\n    contributionsCollection(from: $from, to: $to) {\n      totalCommitContributions\n      totalPullRequestContributions\n      totalIssueContributions\n      totalPullRequestReviewContributions\n    }\n  }\n  reviewRequests: search(\n    query: $reviewRequestQuery\n    type: ISSUE\n    first: $todoFirst\n  ) {\n    issueCount\n    nodes {\n      __typename\n      ... on PullRequest {\n        id\n        number\n        title\n        url\n        updatedAt\n        reviewDecision\n        repository {\n          nameWithOwner\n          url\n        }\n        author {\n          login\n        }\n        comments {\n          totalCount\n        }\n      }\n    }\n  }\n  issueAssignments: search(\n    query: $issueAssignmentQuery\n    type: ISSUE\n    first: $todoFirst\n  ) {\n    issueCount\n    nodes {\n      __typename\n      ... on Issue {\n        id\n        number\n        title\n        url\n        updatedAt\n        state\n        repository {\n          nameWithOwner\n          url\n        }\n        comments {\n          totalCount\n        }\n      }\n    }\n  }\n  authoredPullRequests: search(\n    query: $authoredPrQuery\n    type: ISSUE\n    first: $todoFirst\n  ) {\n    issueCount\n  }\n}",
): (typeof documents)["query Dashboard($from: DateTime!, $to: DateTime!, $recentReposFirst: Int!, $todoFirst: Int!, $reviewRequestQuery: String!, $issueAssignmentQuery: String!, $authoredPrQuery: String!) {\n  viewer {\n    id\n    login\n    name\n    company\n    repositories(\n      first: $recentReposFirst\n      affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]\n      orderBy: {field: PUSHED_AT, direction: DESC}\n      isFork: false\n    ) {\n      totalCount\n      nodes {\n        id\n        name\n        nameWithOwner\n        url\n        updatedAt\n        pushedAt\n        isPrivate\n        primaryLanguage {\n          name\n          color\n        }\n        issues(states: OPEN) {\n          totalCount\n        }\n        pullRequests(states: OPEN) {\n          totalCount\n        }\n      }\n    }\n    contributionsCollection(from: $from, to: $to) {\n      totalCommitContributions\n      totalPullRequestContributions\n      totalIssueContributions\n      totalPullRequestReviewContributions\n    }\n  }\n  reviewRequests: search(\n    query: $reviewRequestQuery\n    type: ISSUE\n    first: $todoFirst\n  ) {\n    issueCount\n    nodes {\n      __typename\n      ... on PullRequest {\n        id\n        number\n        title\n        url\n        updatedAt\n        reviewDecision\n        repository {\n          nameWithOwner\n          url\n        }\n        author {\n          login\n        }\n        comments {\n          totalCount\n        }\n      }\n    }\n  }\n  issueAssignments: search(\n    query: $issueAssignmentQuery\n    type: ISSUE\n    first: $todoFirst\n  ) {\n    issueCount\n    nodes {\n      __typename\n      ... on Issue {\n        id\n        number\n        title\n        url\n        updatedAt\n        state\n        repository {\n          nameWithOwner\n          url\n        }\n        comments {\n          totalCount\n        }\n      }\n    }\n  }\n  authoredPullRequests: search(\n    query: $authoredPrQuery\n    type: ISSUE\n    first: $todoFirst\n  ) {\n    issueCount\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'query RepositoryDetail($owner: String!, $name: String!, $rootExpression: String!, $readmeExpression: String!) {\n  repository(owner: $owner, name: $name) {\n    id\n    name\n    nameWithOwner\n    url\n    description\n    homepageUrl\n    createdAt\n    updatedAt\n    pushedAt\n    isPrivate\n    visibility\n    viewerPermission\n    stargazerCount\n    forkCount\n    watchers {\n      totalCount\n    }\n    issues(states: OPEN) {\n      totalCount\n    }\n    pullRequests(states: OPEN) {\n      totalCount\n    }\n    primaryLanguage {\n      name\n      color\n    }\n    languages(first: 6, orderBy: {field: SIZE, direction: DESC}) {\n      edges {\n        size\n        node {\n          id\n          name\n          color\n        }\n      }\n    }\n    owner {\n      __typename\n      login\n      ... on User {\n        name\n      }\n      ... on Organization {\n        name\n      }\n    }\n    defaultBranchRef {\n      name\n      target {\n        __typename\n        ... on Commit {\n          history(first: 1) {\n            totalCount\n          }\n          committedDate\n          messageHeadline\n          author {\n            name\n            user {\n              login\n              avatarUrl(size: 40)\n              url\n            }\n          }\n        }\n      }\n    }\n    refs(\n      refPrefix: "refs/heads/"\n      first: 10\n      orderBy: {field: ALPHABETICAL, direction: ASC}\n    ) {\n      totalCount\n      nodes {\n        id\n        name\n        target {\n          __typename\n          ... on Commit {\n            committedDate\n            messageHeadline\n            author {\n              name\n              user {\n                login\n              }\n            }\n          }\n        }\n      }\n    }\n    rootEntries: object(expression: $rootExpression) {\n      __typename\n      ... on Tree {\n        entries {\n          name\n          type\n          oid\n          mode\n          object {\n            __typename\n            ... on Blob {\n              byteSize\n              isBinary\n            }\n          }\n        }\n      }\n    }\n    readme: object(expression: $readmeExpression) {\n      __typename\n      ... on Blob {\n        byteSize\n        isBinary\n        text\n      }\n    }\n  }\n}',
): (typeof documents)['query RepositoryDetail($owner: String!, $name: String!, $rootExpression: String!, $readmeExpression: String!) {\n  repository(owner: $owner, name: $name) {\n    id\n    name\n    nameWithOwner\n    url\n    description\n    homepageUrl\n    createdAt\n    updatedAt\n    pushedAt\n    isPrivate\n    visibility\n    viewerPermission\n    stargazerCount\n    forkCount\n    watchers {\n      totalCount\n    }\n    issues(states: OPEN) {\n      totalCount\n    }\n    pullRequests(states: OPEN) {\n      totalCount\n    }\n    primaryLanguage {\n      name\n      color\n    }\n    languages(first: 6, orderBy: {field: SIZE, direction: DESC}) {\n      edges {\n        size\n        node {\n          id\n          name\n          color\n        }\n      }\n    }\n    owner {\n      __typename\n      login\n      ... on User {\n        name\n      }\n      ... on Organization {\n        name\n      }\n    }\n    defaultBranchRef {\n      name\n      target {\n        __typename\n        ... on Commit {\n          history(first: 1) {\n            totalCount\n          }\n          committedDate\n          messageHeadline\n          author {\n            name\n            user {\n              login\n              avatarUrl(size: 40)\n              url\n            }\n          }\n        }\n      }\n    }\n    refs(\n      refPrefix: "refs/heads/"\n      first: 10\n      orderBy: {field: ALPHABETICAL, direction: ASC}\n    ) {\n      totalCount\n      nodes {\n        id\n        name\n        target {\n          __typename\n          ... on Commit {\n            committedDate\n            messageHeadline\n            author {\n              name\n              user {\n                login\n              }\n            }\n          }\n        }\n      }\n    }\n    rootEntries: object(expression: $rootExpression) {\n      __typename\n      ... on Tree {\n        entries {\n          name\n          type\n          oid\n          mode\n          object {\n            __typename\n            ... on Blob {\n              byteSize\n              isBinary\n            }\n          }\n        }\n      }\n    }\n    readme: object(expression: $readmeExpression) {\n      __typename\n      ... on Blob {\n        byteSize\n        isBinary\n        text\n      }\n    }\n  }\n}'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query Viewer {\n  viewer {\n    id\n    login\n    name\n    avatarUrl(size: 80)\n    url\n    company\n  }\n}",
): (typeof documents)["query Viewer {\n  viewer {\n    id\n    login\n    name\n    avatarUrl(size: 80)\n    url\n    company\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query ViewerProfile($from: DateTime!, $to: DateTime!) {\n  viewer {\n    id\n    login\n    name\n    avatarUrl(size: 160)\n    url\n    email\n    company\n    location\n    websiteUrl\n    bio\n    createdAt\n    followers {\n      totalCount\n    }\n    following {\n      totalCount\n    }\n    organizations(first: 10) {\n      totalCount\n      nodes {\n        id\n        login\n        name\n        url\n        avatarUrl(size: 40)\n      }\n    }\n    repositories(\n      first: 5\n      affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]\n      orderBy: {field: PUSHED_AT, direction: DESC}\n      isFork: false\n    ) {\n      totalCount\n      nodes {\n        id\n        name\n        nameWithOwner\n        url\n        viewerPermission\n        updatedAt\n        isPrivate\n      }\n    }\n    contributionsCollection(from: $from, to: $to) {\n      totalCommitContributions\n      totalPullRequestContributions\n      totalIssueContributions\n      totalPullRequestReviewContributions\n    }\n  }\n}",
): (typeof documents)["query ViewerProfile($from: DateTime!, $to: DateTime!) {\n  viewer {\n    id\n    login\n    name\n    avatarUrl(size: 160)\n    url\n    email\n    company\n    location\n    websiteUrl\n    bio\n    createdAt\n    followers {\n      totalCount\n    }\n    following {\n      totalCount\n    }\n    organizations(first: 10) {\n      totalCount\n      nodes {\n        id\n        login\n        name\n        url\n        avatarUrl(size: 40)\n      }\n    }\n    repositories(\n      first: 5\n      affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]\n      orderBy: {field: PUSHED_AT, direction: DESC}\n      isFork: false\n    ) {\n      totalCount\n      nodes {\n        id\n        name\n        nameWithOwner\n        url\n        viewerPermission\n        updatedAt\n        isPrivate\n      }\n    }\n    contributionsCollection(from: $from, to: $to) {\n      totalCommitContributions\n      totalPullRequestContributions\n      totalIssueContributions\n      totalPullRequestReviewContributions\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query ViewerRepositories($first: Int!, $after: String) {\n  viewer {\n    repositories(\n      first: $first\n      after: $after\n      affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]\n      orderBy: {field: PUSHED_AT, direction: DESC}\n    ) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      nodes {\n        id\n        name\n        nameWithOwner\n        url\n        description\n        isPrivate\n        visibility\n        pushedAt\n        updatedAt\n        viewerPermission\n        stargazerCount\n        forkCount\n        primaryLanguage {\n          name\n          color\n        }\n        owner {\n          __typename\n          login\n          avatarUrl(size: 40)\n          ... on Organization {\n            name\n          }\n          ... on User {\n            name\n          }\n        }\n        issues(states: OPEN) {\n          totalCount\n        }\n        pullRequests(states: OPEN) {\n          totalCount\n        }\n        defaultBranchRef {\n          name\n          target {\n            __typename\n            ... on Commit {\n              history(first: 1) {\n                totalCount\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
): (typeof documents)["query ViewerRepositories($first: Int!, $after: String) {\n  viewer {\n    repositories(\n      first: $first\n      after: $after\n      affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]\n      orderBy: {field: PUSHED_AT, direction: DESC}\n    ) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      nodes {\n        id\n        name\n        nameWithOwner\n        url\n        description\n        isPrivate\n        visibility\n        pushedAt\n        updatedAt\n        viewerPermission\n        stargazerCount\n        forkCount\n        primaryLanguage {\n          name\n          color\n        }\n        owner {\n          __typename\n          login\n          avatarUrl(size: 40)\n          ... on Organization {\n            name\n          }\n          ... on User {\n            name\n          }\n        }\n        issues(states: OPEN) {\n          totalCount\n        }\n        pullRequests(states: OPEN) {\n          totalCount\n        }\n        defaultBranchRef {\n          name\n          target {\n            __typename\n            ... on Commit {\n              history(first: 1) {\n                totalCount\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
